name: fullasagoog
favicon: null
layout_spectrum: 0.6048231807071716
typography_spectrum: 0.24695
title: are you fullasagoog?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b100c'
    - '#305b20'
    - '#908c82'
    - '#c1c73a'
  brandStrength: 0.481511271558702
  lightness: 0.8188322857022285
  saturation: 0.405478103319183
  rhythmicContrast: 0.8818662303965539
purpose: []
